import json

products_list = [
  {
    "id": "nse",
    "name": "NSE India Limited (National Stock Exchange)",
    "shortName": "NSE India",
    "code": "ONSE",
    "category": "Financial Services",
    "price": 1985,
    "indicative": True,
    "lotSize": 25,
    "isin": "INE118A01012",
    "status": "DRHP PLANNED",
    "high52": "₹2,250",
    "low52": "₹1,650",
    "marketCap": "₹98,250 Cr",
    "popular": True,
    "description": "National Stock Exchange of India Limited (NSE) is India's leading stock exchange covering various cities and towns across the country.",
    "sector": "Stock Exchange",
    "color": "emerald"
  },
  {
    "id": "otis",
    "name": "OTIS Elevator Company (India) Limited",
    "shortName": "OTIS India",
    "code": "OTIS",
    "category": "Engineering & Industrial",
    "price": 4200,
    "indicative": True,
    "lotSize": 10,
    "isin": "INE003A01018",
    "status": "ACTIVE",
    "high52": "₹4,600",
    "low52": "₹3,400",
    "marketCap": "₹18,500 Cr",
    "popular": True,
    "description": "Otis is the world's leading company for elevator and escalator manufacturing, installation and service.",
    "sector": "Elevator & Heavy Engineering",
    "color": "emerald"
  },
  {
    "id": "motilal-home",
    "name": "Motilal Oswal Home Finance Limited",
    "shortName": "Motilal Home",
    "code": "MOHFL",
    "category": "Financial Services",
    "price": 38,
    "indicative": True,
    "lotSize": 500,
    "isin": "INE489L01017",
    "status": "ACTIVE",
    "high52": "₹45.00",
    "low52": "₹28.00",
    "marketCap": "₹3,800 Cr",
    "popular": False,
    "description": "Motilal Oswal Home Finance Limited is a professionally managed housing finance company registered with National Housing Bank (NHB).",
    "sector": "Housing Finance (HFC)",
    "color": "amber"
  },
  {
    "id": "msei",
    "name": "Metropolitan Stock Exchange (MSEI)",
    "shortName": "MSEI",
    "code": "XMSEI",
    "category": "Financial Services",
    "price": 5.75,
    "indicative": True,
    "lotSize": 1000,
    "isin": "INE342J01019",
    "status": "ACTIVE",
    "high52": "₹7.20",
    "low52": "₹4.10",
    "marketCap": "₹2,840 Cr",
    "popular": True,
    "description": "Metropolitan Stock Exchange of India Limited (MSE) is a recognized electronic stock exchange offering a transparent trading platform.",
    "sector": "Stock Exchange",
    "color": "emerald"
  },
  {
    "id": "boat",
    "name": "Imagine Marketing Limited (boAt Lifestyle)",
    "shortName": "boAt Lifestyle",
    "code": "BOAT",
    "category": "Consumer Tech",
    "price": 855,
    "indicative": True,
    "lotSize": 50,
    "isin": "INE002N01028",
    "status": "DRHP PLANNED",
    "high52": "₹1,020",
    "low52": "₹680",
    "marketCap": "₹12,400 Cr",
    "popular": True,
    "description": "Imagine Marketing Limited (boAt) is India's leading consumer tech and wearable electronics company providing audio and smart accessories.",
    "sector": "Consumer Tech & Wearables",
    "color": "amber"
  },
  {
    "id": "nayara",
    "name": "Nayara Energy Limited (Essar Oil)",
    "shortName": "Nayara Energy",
    "code": "NAYARA",
    "category": "Energy & Power",
    "price": 285,
    "indicative": True,
    "lotSize": 100,
    "isin": "INE011A01019",
    "status": "ACTIVE",
    "high52": "₹340",
    "low52": "₹220",
    "marketCap": "₹42,000 Cr",
    "popular": True,
    "description": "Nayara Energy is an integrated downstream energy company operating the second largest single-site refinery in India at Vadinar, Gujarat.",
    "sector": "Oil Refining & Petrochemicals",
    "color": "emerald"
  },
  {
    "id": "merino",
    "name": "Merino Industries Limited",
    "shortName": "Merino Industries",
    "code": "MERINO",
    "category": "Manufacturing & Materials",
    "price": 2575,
    "indicative": True,
    "lotSize": 25,
    "isin": "INE485B01015",
    "status": "ACTIVE",
    "high52": "₹2,850",
    "low52": "₹2,100",
    "marketCap": "₹6,800 Cr",
    "popular": False,
    "description": "Merino Industries is a leading manufacturer of decorative laminates, interior surface products and processed foods in India.",
    "sector": "Laminates & Building Materials",
    "color": "emerald"
  },
  {
    "id": "ncdex",
    "name": "National Commodity & Derivatives Exchange Limited (NCDEX)",
    "shortName": "NCDEX Limited",
    "code": "NCDEX",
    "category": "Financial Services",
    "price": 378,
    "indicative": True,
    "lotSize": 100,
    "isin": "INE688I01017",
    "status": "ACTIVE",
    "high52": "₹440",
    "low52": "₹290",
    "marketCap": "₹1,950 Cr",
    "popular": True,
    "description": "NCDEX is India's leading agricultural commodity derivatives exchange providing a transparent marketplace for price discovery.",
    "sector": "Commodity Exchange",
    "color": "emerald"
  },
  {
    "id": "oyo",
    "name": "Oravel Stays Limited (OYO Rooms)",
    "shortName": "OYO Rooms",
    "code": "OYO",
    "category": "Hospitality & Travel",
    "price": 42,
    "indicative": True,
    "lotSize": 500,
    "isin": "INE561P01018",
    "status": "DRHP FILED",
    "high52": "₹55.00",
    "low52": "₹32.00",
    "marketCap": "₹28,000 Cr",
    "popular": True,
    "description": "Oravel Stays (OYO) is a global platform empowering entrepreneurs and small businesses with technology to run hospitality operations.",
    "sector": "Hospitality Tech",
    "color": "amber"
  },
  {
    "id": "mohan-meakin",
    "name": "Mohan Meakin Limited",
    "shortName": "Mohan Meakin",
    "code": "MOHAN",
    "category": "Consumer Goods & Beverages",
    "price": 2350,
    "indicative": True,
    "lotSize": 25,
    "isin": "INE516C01018",
    "status": "ACTIVE",
    "high52": "₹2,600",
    "low52": "₹1,850",
    "marketCap": "₹2,050 Cr",
    "popular": True,
    "description": "Mohan Meakin Limited is a historic Indian manufacturing company known for beverages, spirits, fruit juices, and breakfast cereals.",
    "sector": "Beverages & Breweries",
    "color": "emerald"
  },
  {
    "id": "csk",
    "name": "Chennai Super Kings Cricket Limited (CSK)",
    "shortName": "CSK Cricket",
    "code": "CSK",
    "category": "Sports & Entertainment",
    "price": 185,
    "indicative": True,
    "lotSize": 200,
    "isin": "INE014J01017",
    "status": "ACTIVE",
    "high52": "₹220",
    "low52": "₹145",
    "marketCap": "₹5,700 Cr",
    "popular": True,
    "description": "Chennai Super Kings Cricket Limited owns and operates the prestigious Indian Premier League (IPL) cricket franchise Chennai Super Kings.",
    "sector": "Sports & Franchise Entertainment",
    "color": "amber"
  },
  {
    "id": "bira",
    "name": "B9 Beverages Limited (BIRA 91)",
    "shortName": "Bira 91",
    "code": "BIRA",
    "category": "Consumer Goods & Beverages",
    "price": 620,
    "indicative": True,
    "lotSize": 50,
    "isin": "INE003N01016",
    "status": "ACTIVE",
    "high52": "₹740",
    "low52": "₹510",
    "marketCap": "₹4,200 Cr",
    "popular": True,
    "description": "B9 Beverages is a craft beer maker and lifestyle beverage brand behind the popular BIRA 91 beer in India and global markets.",
    "sector": "Craft Breweries & Beverages",
    "color": "emerald"
  },
  {
    "id": "bootes",
    "name": "Bootes Impex Tech Limited",
    "shortName": "Bootes Impex",
    "code": "BOOTES",
    "category": "Infrastructure & Engineering",
    "price": 145,
    "indicative": True,
    "lotSize": 200,
    "isin": "INE018X01012",
    "status": "ACTIVE",
    "high52": "₹175",
    "low52": "₹115",
    "marketCap": "₹920 Cr",
    "popular": False,
    "description": "Bootes Impex Tech delivers sustainable infrastructure, green building constructions, and net-zero engineering solutions.",
    "sector": "Green Construction & Infrastructure",
    "color": "emerald"
  },
  {
    "id": "hero-fincorp",
    "name": "Hero Fincorp Limited",
    "shortName": "Hero Fincorp",
    "code": "HEROFIN",
    "category": "Financial Services",
    "price": 1380,
    "indicative": True,
    "lotSize": 50,
    "isin": "INE957N01016",
    "status": "IPO READY",
    "high52": "₹1,600",
    "low52": "₹1,150",
    "marketCap": "₹18,200 Cr",
    "popular": True,
    "description": "Hero FinCorp is an Indian NBFC and associate company of Hero MotoCorp providing retail, MSME and corporate finance.",
    "sector": "Non-Banking Financial Company (NBFC)",
    "color": "emerald"
  },
  {
    "id": "delta-galaxy",
    "name": "Delta Galaxy Private Limited",
    "shortName": "Delta Galaxy",
    "code": "DELTA",
    "category": "Technology",
    "price": 95,
    "indicative": True,
    "lotSize": 250,
    "isin": "INE0A4M01018",
    "status": "UNLISTED",
    "high52": "₹120",
    "low52": "₹75",
    "marketCap": "₹450 Cr",
    "popular": False,
    "description": "Delta Galaxy provides advanced digital trading, logistics and enterprise data solutions across regional supply chains.",
    "sector": "Information Technology",
    "color": "amber"
  },
  {
    "id": "care-health",
    "name": "Care Health Insurance Limited (Religare Health)",
    "shortName": "Care Health",
    "code": "CARE",
    "category": "Financial Services",
    "price": 280,
    "indicative": True,
    "lotSize": 100,
    "isin": "INE971L01018",
    "status": "ACTIVE",
    "high52": "₹330",
    "low52": "₹210",
    "marketCap": "₹24,500 Cr",
    "popular": True,
    "description": "Care Health Insurance is a specialized standalone health insurer providing health, critical illness and travel insurance.",
    "sector": "Health Insurance",
    "color": "emerald"
  },
  {
    "id": "hinduja-leyland",
    "name": "Hinduja Leyland Finance Limited",
    "shortName": "Hinduja Leyland",
    "code": "HLF",
    "category": "Financial Services",
    "price": 175,
    "indicative": True,
    "lotSize": 200,
    "isin": "INE146O01011",
    "status": "ACTIVE",
    "high52": "₹210",
    "low52": "₹135",
    "marketCap": "₹8,600 Cr",
    "popular": False,
    "description": "Hinduja Leyland Finance is a premier vehicle finance NBFC sponsored by Ashok Leyland and the Hinduja Group.",
    "sector": "Commercial Vehicle Finance",
    "color": "emerald"
  },
  {
    "id": "cial",
    "name": "Cochin International Airport Limited (CIAL)",
    "shortName": "Cochin Airport",
    "code": "CIAL",
    "category": "Infrastructure & Aviation",
    "price": 215,
    "indicative": True,
    "lotSize": 200,
    "isin": "INE079C01014",
    "status": "ACTIVE",
    "high52": "₹260",
    "low52": "₹165",
    "marketCap": "₹8,200 Cr",
    "popular": True,
    "description": "CIAL operates Cochin International Airport, the world's first fully solar-powered airport and India's first PPP airport.",
    "sector": "Airport Infrastructure & Solar",
    "color": "emerald"
  },
  {
    "id": "icl-fincorp",
    "name": "ICL Fincorp Limited",
    "shortName": "ICL Fincorp",
    "code": "ICL",
    "category": "Financial Services",
    "price": 75,
    "indicative": True,
    "lotSize": 300,
    "isin": "INE018U01018",
    "status": "ACTIVE",
    "high52": "₹95",
    "low52": "₹58",
    "marketCap": "₹650 Cr",
    "popular": False,
    "description": "ICL Fincorp is a non-banking financial company offering gold loans, property loans and business credit across India.",
    "sector": "Gold Loans & NBFC",
    "color": "amber"
  },
  {
    "id": "incred",
    "name": "InCred Holdings Limited",
    "shortName": "InCred Holdings",
    "code": "INCRED",
    "category": "Financial Services",
    "price": 220,
    "indicative": True,
    "lotSize": 150,
    "isin": "INE945W01016",
    "status": "ACTIVE",
    "high52": "₹270",
    "low52": "₹180",
    "marketCap": "₹9,100 Cr",
    "popular": True,
    "description": "InCred is a diversified new-age financial services group offering personal loans, MSME lending, wealth and institutional equities.",
    "sector": "Fintech & Diversified NBFC",
    "color": "emerald"
  },
  {
    "id": "apollo-green",
    "name": "Apollo Green Energy Limited",
    "shortName": "Apollo Green",
    "code": "APOLLO",
    "category": "Renewable Energy",
    "price": 88,
    "indicative": True,
    "lotSize": 300,
    "isin": "INE019V01016",
    "status": "ACTIVE",
    "high52": "₹115",
    "low52": "₹65",
    "marketCap": "₹1,150 Cr",
    "popular": False,
    "description": "Apollo Green Energy develops solar farms, battery storage and utility-scale green hydrogen infrastructure projects.",
    "sector": "Solar & Clean Energy EPC",
    "color": "emerald"
  },
  {
    "id": "furlenco",
    "name": "House of Kieraya Limited (Furlenco)",
    "shortName": "Furlenco",
    "code": "FURLENCO",
    "category": "Consumer & Furniture",
    "price": 65,
    "indicative": True,
    "lotSize": 300,
    "isin": "INE021A01012",
    "status": "UNLISTED",
    "high52": "₹85",
    "low52": "₹45",
    "marketCap": "₹950 Cr",
    "popular": False,
    "description": "House of Kieraya (Furlenco) is India's pioneer furniture and home appliance subscription platform.",
    "sector": "E-Commerce & Subscriptions",
    "color": "amber"
  },
  {
    "id": "inox-leasing",
    "name": "Inox Leasing and Finance Limited",
    "shortName": "Inox Leasing",
    "code": "INOX",
    "category": "Financial Services",
    "price": 1450,
    "indicative": True,
    "lotSize": 50,
    "isin": "INE582D01019",
    "status": "ACTIVE",
    "high52": "₹1,750",
    "low52": "₹1,100",
    "marketCap": "₹14,500 Cr",
    "popular": True,
    "description": "Inox Leasing and Finance is a core investment company and holding company of the prominent Inox Group.",
    "sector": "Holding Company & Investments",
    "color": "emerald"
  },
  {
    "id": "transline",
    "name": "Transline Technologies Limited",
    "shortName": "Transline Tech",
    "code": "TRANSLINE",
    "category": "Technology",
    "price": 82,
    "indicative": True,
    "lotSize": 250,
    "isin": "INE022B01010",
    "status": "ACTIVE",
    "high52": "₹105",
    "low52": "₹60",
    "marketCap": "₹420 Cr",
    "popular": False,
    "description": "Transline Technologies delivers smart city automation, biometric identification and public sector IT system integration.",
    "sector": "System Integration & IT Solutions",
    "color": "emerald"
  },
  {
    "id": "ppfas",
    "name": "Parag Parikh Financial Advisory Services (PPFAS)",
    "shortName": "PPFAS Advisory",
    "code": "PPFAS",
    "category": "Financial Services",
    "price": 1650,
    "indicative": True,
    "lotSize": 25,
    "isin": "INE123B01014",
    "status": "ACTIVE",
    "high52": "₹1,950",
    "low52": "₹1,300",
    "marketCap": "₹1,650 Cr",
    "popular": True,
    "description": "PPFAS is the holding company and sponsor of Parag Parikh Mutual Fund, one of India's most respected value-investing asset managers.",
    "sector": "Asset Management & Holdings",
    "color": "emerald"
  },
  {
    "id": "kineco",
    "name": "Kineco Limited (Aerospace & Defence)",
    "shortName": "Kineco Limited",
    "code": "KINECO",
    "category": "Defence & Aerospace",
    "price": 460,
    "indicative": True,
    "lotSize": 100,
    "isin": "INE024C01016",
    "status": "ACTIVE",
    "high52": "₹540",
    "low52": "₹370",
    "marketCap": "₹2,100 Cr",
    "popular": True,
    "description": "Kineco is a premier composite technology manufacturer supplying space, defence, railways and marine infrastructure sectors.",
    "sector": "Composites & Defence Equipment",
    "color": "emerald"
  },
  {
    "id": "esds",
    "name": "ESDS Software Solution Limited",
    "shortName": "ESDS Software",
    "code": "ESDS",
    "category": "Technology",
    "price": 310,
    "indicative": True,
    "lotSize": 100,
    "isin": "INE089N01018",
    "status": "DRHP FILED",
    "high52": "₹380",
    "low52": "₹240",
    "marketCap": "₹2,800 Cr",
    "popular": True,
    "description": "ESDS Software Solution is a leading cloud services and end-to-end data center solutions provider in India.",
    "sector": "Cloud Infrastructure & SaaS",
    "color": "emerald"
  },
  {
    "id": "growest",
    "name": "Growest Industries Limited",
    "shortName": "Growest Ind",
    "code": "GROWEST",
    "category": "Agriculture & Chemicals",
    "price": 55,
    "indicative": True,
    "lotSize": 500,
    "isin": "INE025D01014",
    "status": "UNLISTED",
    "high52": "₹75",
    "low52": "₹40",
    "marketCap": "₹320 Cr",
    "popular": False,
    "description": "Growest Industries produces specialized organic fertilizers, bio-nutrients and agrochemical formulations.",
    "sector": "Agrochemicals & Fertilizers",
    "color": "amber"
  },
  {
    "id": "infra-market",
    "name": "Hella Infra Market Private Limited (Infra.Market)",
    "shortName": "Infra.Market",
    "code": "INFRAMKT",
    "category": "Construction & Materials",
    "price": 820,
    "indicative": True,
    "lotSize": 50,
    "isin": "INE026E01012",
    "status": "IPO READY",
    "high52": "₹980",
    "low52": "₹650",
    "marketCap": "₹22,000 Cr",
    "popular": True,
    "description": "Infra.Market is a premier construction materials company leveraging technology to provide procurement across building products.",
    "sector": "B2B Construction & Building Materials",
    "color": "emerald"
  },
  {
    "id": "indofil",
    "name": "Indofil Industries Limited",
    "shortName": "Indofil Industries",
    "code": "INDOFIL",
    "category": "Chemicals & Agro",
    "price": 890,
    "indicative": True,
    "lotSize": 50,
    "isin": "INE320A01015",
    "status": "ACTIVE",
    "high52": "₹1,050",
    "low52": "₹720",
    "marketCap": "₹5,400 Cr",
    "popular": False,
    "description": "Indofil Industries is an established research-led agrochemicals and specialty chemical manufacturer with global distribution.",
    "sector": "Specialty Chemicals & Crop Care",
    "color": "emerald"
  },
  {
    "id": "gh2-solar",
    "name": "GH2 Solar Limited",
    "shortName": "GH2 Solar",
    "code": "GH2",
    "category": "Renewable Energy",
    "price": 68,
    "indicative": True,
    "lotSize": 400,
    "isin": "INE027F01019",
    "status": "ACTIVE",
    "high52": "₹90",
    "low52": "₹48",
    "marketCap": "₹580 Cr",
    "popular": False,
    "description": "GH2 Solar specializes in green hydrogen generation technology, rooftop solar arrays and distributed clean power EPC.",
    "sector": "Green Hydrogen & Solar EPC",
    "color": "emerald"
  },
  {
    "id": "jupiter-intl",
    "name": "Jupiter International Limited",
    "shortName": "Jupiter Intl",
    "code": "JUPITER",
    "category": "Renewable Energy",
    "price": 540,
    "indicative": True,
    "lotSize": 100,
    "isin": "INE028G01017",
    "status": "DRHP FILED",
    "high52": "₹630",
    "low52": "₹410",
    "marketCap": "₹3,900 Cr",
    "popular": True,
    "description": "Jupiter International is one of India's leading manufacturers of photovoltaic solar cells and green engineering solutions.",
    "sector": "Solar Cell Manufacturing",
    "color": "emerald"
  },
  {
    "id": "ticker-ltd",
    "name": "Ticker Limited",
    "shortName": "Ticker Ltd",
    "code": "TICKER",
    "category": "Technology & Media",
    "price": 45,
    "indicative": True,
    "lotSize": 500,
    "isin": "INE029H01015",
    "status": "UNLISTED",
    "high52": "₹62",
    "low52": "₹33",
    "marketCap": "₹380 Cr",
    "popular": False,
    "description": "Ticker Limited is a financial technology and real-time market data platform providing financial analysis and terminal feeds.",
    "sector": "Fintech & Data Terminal",
    "color": "amber"
  },
  {
    "id": "urban-tots",
    "name": "Urban Tots (V-Bazaar Retail)",
    "shortName": "Urban Tots",
    "code": "URBAN",
    "category": "Consumer & Retail",
    "price": 52,
    "indicative": True,
    "lotSize": 400,
    "isin": "INE030I01011",
    "status": "UNLISTED",
    "high52": "₹70",
    "low52": "₹38",
    "marketCap": "₹290 Cr",
    "popular": False,
    "description": "Urban Tots is a fast-growing retail chain specializing in infant apparel, toys and children's essentials across India.",
    "sector": "Apparel & Kids Retail",
    "color": "amber"
  },
  {
    "id": "onix",
    "name": "Onix Renewable Limited",
    "shortName": "Onix Renewable",
    "code": "onix",
    "category": "Renewable Energy",
    "price": 46,
    "indicative": True,
    "lotSize": 200,
    "isin": "INE0B9D01024",
    "status": "UNLISTED",
    "high52": "₹58.00",
    "low52": "₹34.00",
    "marketCap": "₹620 Cr",
    "popular": False,
    "description": "Onix Renewable Limited is engaged in solar and wind renewable energy generation, EPC contracts, and green energy infrastructure.",
    "sector": "Renewable Energy",
    "color": "amber"
  },
  {
    "id": "bharat-nidhi",
    "name": "Bharat Nidhi Limited (Bennett Coleman Holding)",
    "shortName": "Bharat Nidhi",
    "code": "BHARATNIDHI",
    "category": "Financial Services",
    "price": 11500,
    "indicative": True,
    "lotSize": 5,
    "isin": "INE031J01019",
    "status": "ACTIVE",
    "high52": "₹13,200",
    "low52": "₹9,800",
    "marketCap": "₹3,400 Cr",
    "popular": True,
    "description": "Bharat Nidhi Limited is an investment and holding firm with significant shareholding in Bennett, Coleman and Co. (Times Group).",
    "sector": "Investment Holding Company",
    "color": "emerald"
  },
  {
    "id": "a-one-steel",
    "name": "A One Steel India Limited",
    "shortName": "A One Steel",
    "code": "AONESTEEL",
    "category": "Metals & Mining",
    "price": 95,
    "indicative": True,
    "lotSize": 250,
    "isin": "INE032K01017",
    "status": "ACTIVE",
    "high52": "₹120",
    "low52": "₹72",
    "marketCap": "₹1,450 Cr",
    "popular": False,
    "description": "A One Steel India is an integrated steel manufacturer producing TMT bars, structural steel and billets in southern India.",
    "sector": "Steel & Metallurgy",
    "color": "emerald"
  },
  {
    "id": "goodluck-defence",
    "name": "Goodluck Defence And Aerospace Limited",
    "shortName": "Goodluck Defence",
    "code": "GLDEFENCE",
    "category": "Defence & Aerospace",
    "price": 380,
    "indicative": True,
    "lotSize": 100,
    "isin": "INE033L01015",
    "status": "ACTIVE",
    "high52": "₹450",
    "low52": "₹290",
    "marketCap": "₹1,850 Cr",
    "popular": True,
    "description": "Goodluck Defence and Aerospace manufactures specialized forgings, forged flanges and aerospace structural components.",
    "sector": "Precision Defence Forgings",
    "color": "emerald"
  },
  {
    "id": "goodluck-green",
    "name": "Goodluck Green Energy Limited",
    "shortName": "Goodluck Green",
    "code": "GLGREEN",
    "category": "Renewable Energy",
    "price": 140,
    "indicative": True,
    "lotSize": 200,
    "isin": "INE034M01013",
    "status": "ACTIVE",
    "high52": "₹175",
    "low52": "₹110",
    "marketCap": "₹780 Cr",
    "popular": False,
    "description": "Goodluck Green Energy provides solar module mounting structures, transmission towers and clean infrastructure EPC.",
    "sector": "Solar Structures & EPC",
    "color": "emerald"
  },
  {
    "id": "hdfc-sec",
    "name": "HDFC Securities Limited",
    "shortName": "HDFC Securities",
    "code": "HDFCSEC",
    "category": "Financial Services",
    "price": 12800,
    "indicative": True,
    "lotSize": 5,
    "isin": "INE504B01010",
    "status": "IPO READY",
    "high52": "₹14,500",
    "low52": "₹10,500",
    "marketCap": "₹19,800 Cr",
    "popular": True,
    "description": "HDFC Securities is a leading retail broking firm in India and a subsidiary of HDFC Bank, providing digital equities and wealth management.",
    "sector": "Stock Broking & Wealth",
    "color": "emerald"
  }
]

# Write JS file
js_content = 'export const UNLISTED_SHARES = ' + json.dumps(products_list, indent=2) + ';\n'
with open('src/data/sharesData.js', 'w', encoding='utf-8') as f:
    f.write(js_content)

print(f'Successfully wrote {len(products_list)} official products to src/data/sharesData.js')

# Generate TSV for user's Google Sheet
headers = ['Name', 'Short Name', 'Price', 'Lot Size', 'Available Quantity', 'Image URL', 'Category', 'ISIN', 'Status', '52W High', '52W Low', 'Market Cap', 'Description', 'Popular']
tsv_rows = ['\t'.join(headers)]
for p in products_list:
    row = [
        str(p['name']),
        str(p['shortName']),
        str(p['price']),
        str(p['lotSize']),
        'Available on Desk',
        '',
        str(p['category']),
        str(p['isin']),
        str(p['status']),
        str(p['high52']),
        str(p['low52']),
        str(p['marketCap']),
        str(p['description']).replace('\n', ' ').replace('\r', ''),
        'true' if p['popular'] else 'false'
    ]
    tsv_rows.append('\t'.join(row))

with open('gspinvest_products_sheet.tsv', 'w', encoding='utf-8') as f:
    f.write('\n'.join(tsv_rows))

print('Generated gspinvest_products_sheet.tsv successfully!')
