import { UNLISTED_SHARES } from "../data/sharesData";
import { RESEARCH_ARTICLES } from "../data/marketInsightsData";

export const GLOBAL_SEARCH_ITEMS = [
  // 1. UNLISTED SHARES & PRE-IPO COMPANIES
  ...UNLISTED_SHARES.map((share) => ({
    id: `share-${share.id}`,
    type: "share",
    title: `${share.name}`,
    subtitle: `${share.category} • ISIN: ${share.isin}`,
    category: "Unlisted Shares",
    badge: `₹${share.price.toLocaleString("en-IN")}`,
    keywords: `${share.name} ${share.shortName} ${share.code} ${share.isin} ${share.category} unlisted pre-ipo share stock private equity`,
    data: share,
  })),

  // 2. INVESTMENT PRODUCTS & SERVICES
  {
    id: "service-equity",
    type: "service",
    target: "services",
    title: "Equity & Derivatives Trading",
    subtitle: "NSE/BSE Delivery, Intraday, Futures & Options with advanced terminal access",
    category: "Services",
    badge: "Active Trading",
    keywords: "equity trading derivatives futures options intraday stock broker nse bse delivery",
  },
  {
    id: "service-unlisted",
    type: "service",
    target: "unlisted-shares",
    title: "Pre-IPO & Unlisted Shares Desk",
    subtitle: "Direct off-market institutional access to high-growth private companies",
    category: "Services",
    badge: "Pre-IPO",
    keywords: "unlisted shares pre-ipo esop private equity high growth companies unicorn",
  },
  {
    id: "service-ipo",
    type: "service",
    target: "services",
    title: "IPO Investments & Applications",
    subtitle: "Mainboard & SME IPO bidding with institutional research allocation",
    category: "Services",
    badge: "IPO Desk",
    keywords: "ipo initial public offering sme ipo mainboard bid application allotment",
  },
  {
    id: "service-mf",
    type: "service",
    target: "calculator",
    title: "Mutual Funds & SIP Planning",
    subtitle: "Goal-based SIPs, direct funds, tax-saving ELSS, and SWP monthly cashflow",
    category: "Services",
    badge: "Wealth Planning",
    keywords: "mutual funds sip lumpsum systematic investment plan elss index funds swp",
  },
  {
    id: "service-wealth",
    type: "service",
    target: "services",
    title: "HNIs Wealth Management & Advisory",
    subtitle: "Bespoke multi-asset portfolio advisory and institutional risk management",
    category: "Services",
    badge: "HNI Desk",
    keywords: "wealth management hni high net worth advisory family office portfolio risk",
  },

  // 3. INSURANCE SOLUTIONS
  {
    id: "ins-life",
    type: "insurance",
    target: "insurance",
    title: "Life Insurance (Term & Endowment)",
    subtitle: "Comprehensive life cover, guaranteed returns, and family financial security",
    category: "Insurance",
    badge: "Tax-Free Benefits",
    keywords: "life insurance term insurance plan endowment ulip retirement death cover policy",
  },
  {
    id: "ins-health",
    type: "insurance",
    target: "insurance",
    title: "Health Insurance (Cashless Mediclaim)",
    subtitle: "100% cashless hospital network, zero-copay, and critical illness protection",
    category: "Insurance",
    badge: "Cashless Network",
    keywords: "health insurance mediclaim medical insurance hospitalization critical illness cashless family floater",
  },
  {
    id: "ins-motor",
    type: "insurance",
    target: "insurance",
    title: "Motor Insurance (2W, 4W & Fleet)",
    subtitle: "Comprehensive accidental damage, zero-depreciation, and third-party protection",
    category: "Insurance",
    badge: "Instant Policy",
    keywords: "motor insurance car insurance bike two wheeler commercial vehicle fleet zero dep",
  },
  {
    id: "ins-general",
    type: "insurance",
    target: "insurance",
    title: "General Insurance (Fire & Property)",
    subtitle: "Industrial, factory, warehouse, and residential building loss protection",
    category: "Insurance",
    badge: "Asset Protection",
    keywords: "general insurance fire insurance property insurance warehouse factory building commercial assets",
  },
  {
    id: "ins-gmc",
    type: "insurance",
    target: "insurance",
    title: "GMC Insurance (Group Mediclaim)",
    subtitle: "Customized corporate health & medical coverage for company employees",
    category: "Insurance",
    badge: "Corporate HR",
    keywords: "gmc insurance group mediclaim employee health corporate medical policy staff insurance",
  },
  {
    id: "ins-topup",
    type: "insurance",
    target: "insurance",
    title: "Top-up & Super Top-up Policy",
    subtitle: "High sum insured enhancement up to ₹1 Crore at minimal incremental premium",
    category: "Insurance",
    badge: "High Sum Insured",
    keywords: "top up super topup policy deductible medical enhancement high sum insured",
  },
  {
    id: "ins-pa",
    type: "insurance",
    target: "insurance",
    title: "PA Policy (Personal Accident)",
    subtitle: "24/7 global accidental cover with permanent disability and income shield",
    category: "Insurance",
    badge: "Accident Cover",
    keywords: "pa policy personal accident accidental death permanent disability income protection",
  },
  {
    id: "ins-marine",
    type: "insurance",
    target: "insurance",
    title: "Marine & Transit Insurance",
    subtitle: "Sea, air, rail, and road cargo loss protection for exporters and importers",
    category: "Insurance",
    badge: "Cargo & Transit",
    keywords: "marine insurance transit cargo export import shipping logistic freight loss",
  },

  // 4. LOAN SOLUTIONS
  {
    id: "loan-home",
    type: "loan",
    target: "loans",
    title: "Home Loan Solutions",
    subtitle: "Lowest interest rates, flexible tenure up to 30 years, and balance transfers",
    category: "Loans",
    badge: "Low ROI",
    keywords: "home loan housing loan property purchase flat balance transfer mortgage construction",
  },
  {
    id: "loan-business",
    type: "loan",
    target: "loans",
    title: "Business & MSME Loans",
    subtitle: "Unsecured business funding, machinery financing, and working capital limits",
    category: "Loans",
    badge: "Quick Disbursal",
    keywords: "business loan msme loan working capital unsecured loan machinery commercial finance",
  },
  {
    id: "loan-lap",
    type: "loan",
    target: "loans",
    title: "Loan Against Property (LAP)",
    subtitle: "Unlock maximum liquidity against commercial, industrial, or residential properties",
    category: "Loans",
    badge: "High Value",
    keywords: "loan against property lap mortgage loan collateral property liquidity",
  },
  {
    id: "loan-personal",
    type: "loan",
    target: "loans",
    title: "Personal Loan",
    subtitle: "Instant approval, minimal documentation, and flexible repayment EMIs",
    category: "Loans",
    badge: "Zero Collateral",
    keywords: "personal loan instant loan instant cash emergency funds personal credit",
  },
  {
    id: "loan-auto",
    type: "loan",
    target: "loans",
    title: "Auto & Car Loan",
    subtitle: "Up to 100% on-road financing for new and certified pre-owned vehicles",
    category: "Loans",
    badge: "Vehicle Finance",
    keywords: "auto loan car loan vehicle finance four wheeler commercial car financing",
  },
  {
    id: "loan-edu",
    type: "loan",
    target: "loans",
    title: "Education Loan",
    subtitle: "Complete tuition, living expense, and overseas study loan solutions",
    category: "Loans",
    badge: "Higher Studies",
    keywords: "education loan student loan overseas study higher education college fee financing",
  },
  {
    id: "loan-gold",
    type: "loan",
    target: "loans",
    title: "Gold Loan",
    subtitle: "Instant disbursal against gold jewellery with highest per-gram value",
    category: "Loans",
    badge: "Instant Cash",
    keywords: "gold loan jewel loan instant gold cash per gram rate",
  },
  {
    id: "loan-sme",
    type: "loan",
    target: "loans",
    title: "SME & Working Capital Finance",
    subtitle: "Overdraft (OD), Cash Credit (CC), and letter of credit trade limits",
    category: "Loans",
    badge: "Trade Limits",
    keywords: "sme loan working capital od cc cash credit overdraft trade limit",
  },

  // 5. CALCULATORS & FINANCIAL TOOLS
  {
    id: "calc-sip",
    type: "calculator",
    target: "calculator",
    title: "SIP Wealth Calculator",
    subtitle: "Calculate expected returns, compounding growth, and future corpus for SIPs",
    category: "Calculators",
    badge: "Interactive Tool",
    keywords: "sip calculator mutual fund calculator return calculator compounding interest wealth builder",
  },
  {
    id: "calc-lumpsum",
    type: "calculator",
    target: "calculator",
    title: "Lumpsum Investment Calculator",
    subtitle: "Project returns on one-time investment with custom expected return rate",
    category: "Calculators",
    badge: "One-Time Wealth",
    keywords: "lumpsum calculator one time investment compounding returns calculator",
  },
  {
    id: "calc-swp",
    type: "calculator",
    target: "calculator",
    title: "SWP (Systematic Withdrawal) Calculator",
    subtitle: "Calculate monthly regular pension and cashflow from mutual fund investments",
    category: "Calculators",
    badge: "Monthly Cashflow",
    keywords: "swp calculator systematic withdrawal plan regular income pension monthly payout",
  },

  // 6. RESEARCH & MARKET INSIGHTS
  ...RESEARCH_ARTICLES.map((art) => ({
    id: `article-${art.id}`,
    type: "article",
    title: art.title,
    subtitle: `${art.category || art.tag} • ${art.readTime || '3 min read'}`,
    category: "Market Insights",
    badge: art.tag || "Research",
    keywords: `${art.title} ${art.tag} ${art.category} research article unlisted insight analysis`,
    data: art,
  })),

  // 7. CAREERS & RECRUITMENT
  {
    id: "career-sales",
    type: "careers",
    title: "Careers: Sales Executive (B2B & B2C)",
    subtitle: "Full-Time • Vasai West Mumbai • ₹25,000 – ₹30,000 / month • 3+ Years Exp",
    category: "Careers",
    badge: "We're Hiring",
    keywords: "careers job hiring sales executive b2b b2c vacancy employment opening recruitment",
  },

  // 8. INVESTOR DESKS & STATUTORY OPERATIONS
  {
    id: "op-demat",
    type: "register",
    title: "Open Free Demat Account",
    subtitle: "Zero 1st Year AMC, instant paperless Aadhaar eKYC account opening",
    category: "Investor Services",
    badge: "100% Free",
    keywords: "open demat account demat trading registration create account ekyc aadhaar",
  },
  {
    id: "op-kyc",
    type: "service",
    target: "services-centre",
    title: "KYC Updation Desk",
    subtitle: "Update address, mobile number, bank account details, and nominees",
    category: "Investor Services",
    badge: "Operations",
    keywords: "kyc update address change bank change mobile update nominee modification",
  },
  {
    id: "op-cdsl",
    type: "external",
    url: "https://evoting.cdslindia.com/Evoting/EvotingLogin",
    title: "CDSL E-Voting Portal",
    subtitle: "Official e-voting portal for CDSL demat account holders and shareholders",
    category: "Statutory Portals",
    badge: "External Link",
    keywords: "cdsl evoting e-voting voting shareholder annual general meeting resolution",
  },
  {
    id: "op-nsdl",
    type: "external",
    url: "https://www.evoting.nsdl.com/",
    title: "NSDL E-Voting Portal",
    subtitle: "Official e-voting portal for NSDL depository participants and investors",
    category: "Statutory Portals",
    badge: "External Link",
    keywords: "nsdl evoting e-voting voting shareholder agm resolution login",
  },

  // 9. CORPORATE, CONTACT & LEGAL
  {
    id: "corp-about",
    type: "scroll",
    target: "about",
    title: "About GSP Investment Pvt. Ltd.",
    subtitle: "7+ Years of Market Mastery, Institutional Governance & Wealth Advisory",
    category: "Company",
    badge: "Since 2025",
    keywords: "about us gsp investment company history founders experience governance mastery",
  },
  {
    id: "corp-contact",
    type: "scroll",
    target: "contact",
    title: "Contact & Head Office Desk",
    subtitle: "A-302 Aparna Niwas, Vasai West • Helpline: 0250 359 4768 • WhatsApp: +91 9096993499",
    category: "Support",
    badge: "Help Desk",
    keywords: "contact support phone email address helpline whatsapp 02503594768 9096993499 vasai mumbai",
  },
  {
    id: "legal-disclaimer",
    type: "legal",
    tab: "disclaimer",
    title: "Disclaimer & Risk Disclosure",
    subtitle: "Statutory market risks, unlisted shares notice, and regulatory compliance",
    category: "Legal",
    badge: "Mandatory Notice",
    keywords: "disclaimer risk disclosure regulatory legal compliance notice",
  },
  {
    id: "legal-terms",
    type: "legal",
    tab: "terms",
    title: "Terms of Use & Service Agreement",
    subtitle: "Electronic record terms under Information Technology Act, 2000",
    category: "Legal",
    badge: "IT Act 2000",
    keywords: "terms of use terms and conditions agreement policy user rules",
  },
  {
    id: "legal-privacy",
    type: "legal",
    tab: "privacy",
    title: "Privacy Policy & Data Security",
    subtitle: "SPDI Rules 2011 compliance, SSL encryption, and strict zero-sale data policy",
    category: "Legal",
    badge: "Data Protection",
    keywords: "privacy policy data protection security cookies encryption confidentiality",
  },
];

export function searchGlobalIndex(query) {
  if (!query || !query.trim()) return [];
  const cleanQ = query.trim().toLowerCase();
  const words = cleanQ.split(/\s+/).filter(Boolean);

  return GLOBAL_SEARCH_ITEMS.filter((item) => {
    const fullText = `${item.title} ${item.subtitle} ${item.category} ${item.keywords || ""}`.toLowerCase();
    return words.every((word) => fullText.includes(word));
  }).slice(0, 12);
}
